app_group:
  - read:
      path: /apps/components.eda.nokia.com
      method: GET

intent_targets:
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/chassis/{name}/_targets
      method: GET
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/components/{name}/_targets
      method: GET
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/controlmodules/{name}/_targets
      method: GET
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/fabricmodules/{name}/_targets
      method: GET
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/fans/{name}/_targets
      method: GET
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/interfacemodules/{name}/_targets
      method: GET
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/monitors/{name}/_targets
      method: GET
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/powersupplies/{name}/_targets
      method: GET

k8_s_topology_request:
  - create:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/monitors/{name}/_topology
      method: POST

resource_history:
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/chassis/{name}/_revs
      method: GET
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/components/{name}/_revs
      method: GET
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/controlmodules/{name}/_revs
      method: GET
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/fabricmodules/{name}/_revs
      method: GET
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/fans/{name}/_revs
      method: GET
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/interfacemodules/{name}/_revs
      method: GET
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/monitors/{name}/_revs
      method: GET
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/powersupplies/{name}/_revs
      method: GET

resource_list:
  - read:
      path: /apps/components.eda.nokia.com/v2
      method: GET

status:
  - delete:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/monitors/{name}
      method: DELETE

ui_result:
  - read:
      path: /apps/components.eda.nokia.com/v2/_ui/{pathname}
      method: GET

com.nokia.eda.components.v2.chassis:
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/chassis/{name}
      method: GET

com.nokia.eda.components.v2.chassis_list:
  - read:
      path: /apps/components.eda.nokia.com/v2/chassis
      method: GET
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/chassis
      method: GET

com.nokia.eda.components.v2.component:
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/components/{name}
      method: GET

com.nokia.eda.components.v2.component_list:
  - read:
      path: /apps/components.eda.nokia.com/v2/components
      method: GET
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/components
      method: GET

com.nokia.eda.components.v2.control_module:
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/controlmodules/{name}
      method: GET

com.nokia.eda.components.v2.control_module_list:
  - read:
      path: /apps/components.eda.nokia.com/v2/controlmodules
      method: GET
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/controlmodules
      method: GET

com.nokia.eda.components.v2.fabric_module:
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/fabricmodules/{name}
      method: GET

com.nokia.eda.components.v2.fabric_module_list:
  - read:
      path: /apps/components.eda.nokia.com/v2/fabricmodules
      method: GET
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/fabricmodules
      method: GET

com.nokia.eda.components.v2.fan:
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/fans/{name}
      method: GET

com.nokia.eda.components.v2.fan_list:
  - read:
      path: /apps/components.eda.nokia.com/v2/fans
      method: GET
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/fans
      method: GET

com.nokia.eda.components.v2.interface_module:
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/interfacemodules/{name}
      method: GET

com.nokia.eda.components.v2.interface_module_list:
  - read:
      path: /apps/components.eda.nokia.com/v2/interfacemodules
      method: GET
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/interfacemodules
      method: GET

com.nokia.eda.components.v2.monitor:
  - create:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/monitors
      method: POST
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/monitors/{name}
      method: GET
  - update:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/monitors/{name}
      method: PUT
  - update:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/monitors/{name}
      method: PATCH

com.nokia.eda.components.v2.monitor_list:
  - read:
      path: /apps/components.eda.nokia.com/v2/monitors
      method: GET
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/monitors
      method: GET
  - delete:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/monitors
      method: DELETE

com.nokia.eda.components.v2.monitor_deleted_resources:
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/monitors/_deleted
      method: GET

com.nokia.eda.components.v2.power_supply:
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/powersupplies/{name}
      method: GET

com.nokia.eda.components.v2.power_supply_list:
  - read:
      path: /apps/components.eda.nokia.com/v2/namespaces/{namespace}/powersupplies
      method: GET
  - read:
      path: /apps/components.eda.nokia.com/v2/powersupplies
      method: GET

totalPaths: 45
totalSchemas: 87
usedSchemas: 24
unusedSchemas: 63
unusedSchemaList:
  - AppGroupVersion
  - ErrorResponse
  - IntentTarget
  - K8SPatchOp
  - OverlayState
  - Patch
  - Resource
  - ResourceHistoryEntry
  - ResourceTopology
  - StatusDetails
  - TopoAttrMetadata
  - TopoAttribute
  - TopoBoolExpression
  - TopoBoolLiteral
  - TopoElemMetadata
  - TopoEndpointBoolExpression
  - TopoField
  - TopoFixedBoolExpression
  - TopoLabelSelector
  - TopoLiteralStatusOrBadge
  - TopoLiteralValue
  - TopoLogicalExpression
  - TopoNodeGrouping
  - TopoOverlayEndpoint
  - TopoOverlayEndpointState
  - TopoOverlayLink
  - TopoOverlayLinkGroup
  - TopoOverlayLinkGroupEndpoint
  - TopoOverlayLinkState
  - TopoOverlayNode
  - TopoOverlayNodeOrGroup
  - TopoOverlayNodeState
  - TopoOverlayValue
  - TopoSchema
  - TopoStateFilter
  - TopoValue
  - TopoValueExpression
  - Topology
  - com.nokia.eda.components.v2.Chassis_alarms
  - com.nokia.eda.components.v2.Chassis_deviations
  - com.nokia.eda.components.v2.Chassis_metadata
  - com.nokia.eda.components.v2.Component_alarms
  - com.nokia.eda.components.v2.Component_deviations
  - com.nokia.eda.components.v2.Component_metadata
  - com.nokia.eda.components.v2.ControlModule_alarms
  - com.nokia.eda.components.v2.ControlModule_deviations
  - com.nokia.eda.components.v2.ControlModule_metadata
  - com.nokia.eda.components.v2.FabricModule_alarms
  - com.nokia.eda.components.v2.FabricModule_deviations
  - com.nokia.eda.components.v2.FabricModule_metadata
  - com.nokia.eda.components.v2.Fan_alarms
  - com.nokia.eda.components.v2.Fan_deviations
  - com.nokia.eda.components.v2.Fan_metadata
  - com.nokia.eda.components.v2.InterfaceModule_alarms
  - com.nokia.eda.components.v2.InterfaceModule_deviations
  - com.nokia.eda.components.v2.InterfaceModule_metadata
  - com.nokia.eda.components.v2.Monitor_DeletedResourceEntry
  - com.nokia.eda.components.v2.Monitor_alarms
  - com.nokia.eda.components.v2.Monitor_deviations
  - com.nokia.eda.components.v2.Monitor_metadata
  - com.nokia.eda.components.v2.PowerSupply_alarms
  - com.nokia.eda.components.v2.PowerSupply_deviations
  - com.nokia.eda.components.v2.PowerSupply_metadata
